### ISSUE TITLE
loop_closure_handler.cpp line 144

### ISSUE THREAD

**Issue by gzyabc** [MISTLab/Intensity_based_LiDAR_SLAM#2]
Thank you for your excellent work. I have some questions about the code. The min index here is less than 6, which I don't quite understand. Is it required to return to the starting position of the robot before the loop detection is calculated? Doesn't it count when I run into a loopback check in the middle?
   ROS_INFO("find loop: %i", min_index);
        if(min_index < 6){
            return min_index;
        }

**Comment by SnowCarter** [comment]
Thanks for pointing this problem. This was a test which I forgot to delete. It should be disabled. In our algorithm, we provided three different methods (ScanContext, ORB, KDTree) for loop detection. You are welcome to try other two methods to find a better one.

**Comment by gzyabc** [comment]
> Thanks for pointing this problem. This was a test which I forgot to delete. It should be disabled. In our algorithm, we provided three different methods (ScanContext, ORB, KDTree) for loop detection. You are welcome to try other two methods to find a better one.

Understand. Thank you again for your excellent work

**Comment by SnowCarter** [comment]
Thank you! I appreciate your kind words. If you have any more questions, feel free to ask.
