### ISSUE TITLE
is it possible to use in melodic?

### ISSUE THREAD

**Issue by himhan34** [MISTLab/Intensity_based_LiDAR_SLAM#4]
happy new year!

**Comment by himhan34** [comment]
how can i get the intensity odometry ? 
Can you tell me?

**Comment by SnowCarter** [comment]
Hi, Happy New Year. Please refer to [q_w_curr and t_w_curr](https://github.com/MISTLab/Intensity_based_LiDAR_SLAM/blob/e4c3b0c868a9ca46930d6087d09f3e6e64980c6f/src/mapOptimization.cpp#L20-L21).

**Comment by himhan34** [comment]
thanks for answering.
