### ISSUE TITLE
Problem about Eigen

### ISSUE THREAD

**Issue by Yiiboo-w** [MISTLab/Intensity_based_LiDAR_SLAM#6]
Excellent work!
Today I tested this work with the provided spot_corridor.bag, but I met the Eigen problem.
My terminal returns the following logs:
![Screenshot from 2024-05-27 20-22-50](https://github.com/MISTLab/Intensity_based_LiDAR_SLAM/assets/91960557/0a6f08c5-4b90-473d-96ba-670817573dc2)
Do you know what caused it? Are there any dependencies updated? Thanks for your help!

**Comment by SnowCarter** [comment]
Hi, I did not update any dependencies. How about trying the Docker version?

**Comment by Yiiboo-w** [comment]
> Hi, I did not update any dependencies. How about trying the Docker version?

Thanks so much for your quick response! I tried the Docker version and it works normally now.

**Comment by SnowCarter** [comment]
That's great.
