### ISSUE TITLE
Parameter Tuning

### ISSUE THREAD

**Issue by Chaoyue-cpu** [MISTLab/Intensity_based_LiDAR_SLAM#8]
Thank you for sharing. I encountered a Y-axis offset issue while running in the tunnel. Do you have any suggestions for parameter tuning? Thanks
![2024-12-02 11-21-15 的屏幕截图](https://github.com/user-attachments/assets/321ddd5c-c31a-4913-9a43-9862534db9a0)

**Comment by SnowCarter** [comment]
Hi, I’ve noticed that the texture information in the intensity image is insufficient for robust ORB feature matching. I recommend exploring machine learning-based feature detection methods, such as [xfeat](https://github.com/verlab/accelerated_features), as a potential replacement for ORB features. This could enhance the matching accuracy by leveraging more discriminative feature points.

**Comment by Chaoyue-cpu** [comment]
> 嗨，我注意到强度图像中的纹理信息不足以进行稳健的 ORB 特征匹配。我建议探索基于机器学习的特征检测方法，例如 [xfeat](https://github.com/verlab/accelerated_features)，作为 ORB 特征的潜在替代品。这可以通过利用更多的判别性特征点来提高匹配准确性。

Thank you very much for your suggestion. I will give it a  try.

**Comment by SnowCarter** [comment]
It's my pleasure! If it works well, you are welcome to push your changes to this repository.
